[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build:css && npx pnpm build:remix"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
