[build]
  command = "npm run build:css && npm run build:remix"
  publish = "public"

[dev]
  command = "remix watch"
  port = 2000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
