# https://taskfile.dev

version: "3"

tasks:
  up:
    cmds:
      - pnpm deps:up
  down:
    cmds:
      - pnpm deps:down
  restart:
    cmds:
      - pnpm deps:restart
  dev:
    deps: [up]
    cmds:
      - pnpm dev
